experiment:
    id: p_
    seed: 1324

##Data
data:
#    ft-path: "/home/matt/data_dummy/cityscapes/" # path to dataset for fine tuning
#    ft-path: "/home/matt/data/ipb_car/2019-11-25_second_recording/images/"
    ft-path: "/home/matt/data/kitti_sem/"

##Training
train:
    mode: 'train'
#    mode: 'infer'
    n_gpus: 1
    workers: 8
    max_epoch: 200
    lr: [0.0005, 0.001, 0.0008, 0.0008]
    batch_size: 32
    overfit: False
    validation_warmup: 10

##Network
model:
    dropout: 0.15
    initialization: "xavier" # one among None, he, xavier

tasks:
    semantic_segmentation:
        n_classes: 12
