experiment:
    id: p_
    seed: 1324

##Data
data:
    ft-path: "~/data/cityscapes/" # path to dataset for fine tuning

##Training
train:
    mode: 'train' 
    n_gpus: 1
    workers: 12
    max_epoch: 100
    lr: [0.001, 0.001, 0.0008, 0.0008]
    batch_size: 8
    overfit: False
    validation_warmup: 10

##Network
model:
    dropout: 0.15
    initialization: "xavier" # one among None, he, xavier

tasks:
    semantic_segmentation:
        n_classes: 20
